# Generated by Django 4.1.5 on 2024-08-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
